// Nguồn dữ liệu duy nhất: index.html và build.mjs cùng đọc file này.
export const slugify = s => String(s)
  .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  .replace(/đ/g, 'd').replace(/Đ/g, 'D')
  .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

export const TERMS = [
  {name:'API', icon:'🍽️', cat:'Web', brief:'Người phục vụ giúp hai phần mềm nói chuyện.', plain:'API là cánh cửa có quy tắc để một ứng dụng yêu cầu dữ liệu hoặc việc gì đó từ ứng dụng khác.', analogy:'Hãy hình dung bạn không vào bếp tự nấu: bạn gọi món với người phục vụ. Họ chuyển đúng yêu cầu vào bếp và mang kết quả ra.', related:['Frontend','Backend','Server']},
  {name:'Database', icon:'🗄️', cat:'Dữ liệu', brief:'Tủ hồ sơ được sắp xếp để tìm lại thật nhanh.', plain:'Database là nơi lưu trữ dữ liệu có tổ chức: tài khoản, sản phẩm, đơn hàng, bài viết…', analogy:'Nó như kho hồ sơ của thư viện: mỗi thứ có vị trí riêng, nên cần là tìm được thay vì lục tung mọi thứ.', related:['Server','Backend','Cache']},
  {name:'Server', icon:'🏢', cat:'Web', brief:'Nơi luôn trực để trả lời yêu cầu từ người dùng.', plain:'Server là máy tính hoặc chương trình cung cấp dữ liệu, xử lý yêu cầu và gửi kết quả về cho thiết bị của bạn.', analogy:'Giống quầy bếp luôn mở: bạn đặt món từ điện thoại, quầy bếp nhận đơn, làm món rồi gửi lại.', related:['API','Cloud','Database']},
  {name:'Frontend', icon:'🪟', cat:'Phát triển', brief:'Phần bạn nhìn và trực tiếp bấm vào.', plain:'Frontend là giao diện website hoặc ứng dụng chạy trước mắt người dùng.', analogy:'Đây là sảnh, menu và nút bấm của một cửa hàng — thứ khách thấy và tương tác.', related:['Backend','UI/UX','API']},
  {name:'Backend', icon:'⚙️', cat:'Phát triển', brief:'Phần hậu trường xử lý mọi việc phía sau.', plain:'Backend chứa logic, dữ liệu và các quy tắc vận hành để ứng dụng hoạt động đúng.', analogy:'Nếu frontend là mặt tiền cửa hàng thì backend là kho, sổ sách và đội vận hành bên trong.', related:['Frontend','Server','Database']},
  {name:'Cloud', icon:'☁️', cat:'Hạ tầng', brief:'Thuê tài nguyên máy tính qua Internet.', plain:'Cloud cho phép bạn dùng máy chủ, lưu trữ hay phần mềm của nhà cung cấp thay vì tự mua và chăm máy.', analogy:'Như thuê căn hộ có sẵn điện nước thay vì tự mua đất, xây nhà và bảo trì từng thứ.', related:['Server','Deploy','Database']},
  {name:'Cache', icon:'⚡', cat:'Hiệu năng', brief:'Ngăn để đồ hay dùng, giúp lấy nhanh hơn.', plain:'Cache giữ tạm dữ liệu thường xuyên được dùng để lần sau không cần tính hoặc tải lại từ đầu.', analogy:'Bạn để chìa khóa ở một cái khay cạnh cửa, thay vì mỗi lần ra ngoài lại đi tìm khắp nhà.', related:['Database','Server','API']},
  {name:'Git', icon:'🕰️', cat:'Công cụ', brief:'Cỗ máy thời gian cho mã nguồn.', plain:'Git lưu các mốc thay đổi của dự án và giúp nhiều người làm cùng nhau mà không mất công việc.', analogy:'Như Google Docs có lịch sử chỉnh sửa, nhưng mạnh hơn và dành cho việc làm phần mềm.', related:['Deploy','Backend','Frontend']},
  {name:'Deploy', icon:'🚀', cat:'Hạ tầng', brief:'Đưa sản phẩm từ máy làm việc đến nơi người dùng dùng được.', plain:'Deploy là quá trình phát hành phiên bản ứng dụng để nó chạy ở môi trường thật.', analogy:'Nấu xong trong bếp chưa đủ; deploy là lúc đưa món ra quầy để khách có thể gọi.', related:['Cloud','Server','Git']},
  {name:'Bug', icon:'🐛', cat:'Cơ bản', brief:'Lỗi khiến sản phẩm hoạt động không đúng ý.', plain:'Bug là sai sót trong mã, dữ liệu hoặc thiết kế gây ra hành vi ngoài dự tính.', analogy:'Như công thức ghi nhầm một muỗng muối thành một bát muối: mọi bước vẫn làm, nhưng kết quả sai.', related:['Debug','Git','Backend']},
  {name:'Debug', icon:'🔎', cat:'Cơ bản', brief:'Tìm và sửa nguyên nhân của lỗi.', plain:'Debug là công việc quan sát, đặt giả thuyết và kiểm tra để biết vì sao bug xảy ra.', analogy:'Giống thợ sửa xe lần theo dấu hiệu để biết xe không nổ máy vì hết xăng, yếu bình hay hỏng bugi.', related:['Bug','Git','Backend']},
  {name:'UI/UX', icon:'✨', cat:'Thiết kế', brief:'Làm sản phẩm vừa đẹp, vừa dễ dùng.', plain:'UI là giao diện nhìn thấy; UX là toàn bộ trải nghiệm khi một người cố hoàn thành việc gì đó.', analogy:'UI là màu sơn và biển chỉ dẫn của quán; UX là việc khách có tìm được bàn, gọi món và thanh toán thoải mái không.', related:['Frontend','API','Backend']},

  {name:'AI', icon:'🤖', cat:'AI', brief:'Máy tính làm được những việc trước đây cần con người.', plain:'AI là tên gọi chung cho các chương trình có thể nhận diện, suy luận, dự đoán hoặc tạo ra nội dung, thay vì chỉ chạy theo lệnh viết cứng.', analogy:'Máy tính bỏ túi chỉ làm đúng phép bạn bấm. AI giống người học việc: nhìn thật nhiều ví dụ rồi tự rút ra cách làm, kể cả với tình huống chưa gặp bao giờ.', related:['Machine Learning','LLM','Dataset']},
  {name:'Machine Learning', icon:'📈', cat:'AI', brief:'Học từ ví dụ thay vì được lập trình từng bước.', plain:'Machine Learning là cách dạy máy tự tìm ra quy luật từ dữ liệu, thay vì bắt con người viết sẵn mọi quy tắc.', analogy:'Bạn không dạy trẻ nhận ra con mèo bằng cách tả từng sợi râu, mà chỉ cho xem thật nhiều con mèo. Máy cũng học đúng kiểu đó.', related:['AI','Dataset','Training']},
  {name:'Deep Learning', icon:'🧠', cat:'AI', brief:'Máy học bằng mạng nhiều tầng, hiểu được thứ phức tạp.', plain:'Deep Learning là nhánh của Machine Learning dùng mạng nơ-ron nhiều tầng để học các mẫu phức tạp như ảnh, âm thanh và ngôn ngữ.', analogy:'Như dây chuyền nhiều công đoạn: tầng đầu chỉ nhận ra đường nét, tầng giữa ghép thành mắt mũi, tầng cuối mới kết luận đó là khuôn mặt ai.', related:['Machine Learning','Neural Network','Model']},
  {name:'Neural Network', icon:'🕸️', cat:'AI', brief:'Mạng các nút tính toán mô phỏng tế bào thần kinh.', plain:'Neural network gồm nhiều nút nối với nhau; mỗi nút nhận tín hiệu, cân nhắc theo trọng số riêng rồi truyền tiếp cho tầng sau.', analogy:'Như hội đồng chấm thi nhiều vòng: mỗi người cho ý kiến với mức tin cậy khác nhau, qua đủ vòng mới chốt được kết luận.', related:['Deep Learning','Model','Training']},
  {name:'Model', icon:'🧮', cat:'AI', brief:'Thành quả sau khi học xong, đem ra dùng được.', plain:'Model là tập tham số đã học được từ dữ liệu, dùng để dự đoán hoặc tạo ra nội dung mới.', analogy:'Giống công thức nấu ăn đúc kết sau nhiều lần thử: bản thân nó không phải món ăn, nhưng cứ theo đó là nấu ra được.', related:['Training','Machine Learning','Inference']},
  {name:'Training', icon:'🏋️', cat:'AI', brief:'Giai đoạn cho máy xem dữ liệu để học.', plain:'Training là quá trình đưa dữ liệu vào, đo xem sai bao nhiêu rồi chỉnh dần tham số, lặp lại cho tới khi model đủ tốt.', analogy:'Như luyện thi: làm đề, dò đáp án, biết sai chỗ nào thì sửa, lặp đi lặp lại cho tới khi chắc tay.', related:['Model','Dataset','Fine-tuning']},
  {name:'Dataset', icon:'📚', cat:'AI', brief:'Kho ví dụ dùng để dạy và kiểm tra máy.', plain:'Dataset là tập dữ liệu đã thu thập và sắp xếp để huấn luyện hoặc đánh giá model.', analogy:'Giống bộ đề ôn thi: đề càng sát thực tế và càng đa dạng thì học xong càng làm được nhiều dạng bài.', related:['Training','Machine Learning','Bias']},
  {name:'LLM', icon:'💬', cat:'AI', brief:'Mô hình ngôn ngữ lớn, thứ đứng sau các chatbot.', plain:'LLM là model được huấn luyện trên lượng văn bản khổng lồ để hiểu và tạo ra ngôn ngữ tự nhiên.', analogy:'Như người đã đọc gần hết thư viện: không nhớ từng trang, nhưng thấm được cách chữ nghĩa thường đi với nhau nên viết tiếp rất trôi.', related:['Prompt','Token','Hallucination']},
  {name:'Prompt', icon:'✍️', cat:'AI', brief:'Câu bạn nhập vào để bảo AI làm gì.', plain:'Prompt là phần mô tả yêu cầu, bối cảnh và ràng buộc mà bạn gửi cho model để nhận về kết quả mong muốn.', analogy:'Như đặt hàng thợ may: nói rõ dáng, vải và số đo thì đồ về vừa vặn; nói qua loa thì nhận lại thứ hên xui.', related:['LLM','Context window','Token']},
  {name:'Token', icon:'🧩', cat:'AI', brief:'Mẩu chữ nhỏ mà AI thực sự đọc.', plain:'Model không đọc theo từ mà cắt văn bản thành các token, mỗi token là một mẩu ký tự. Chi phí và giới hạn độ dài đều tính theo token.', analogy:'Như đếm tiền theo tờ chứ không theo câu chuyện: dài hay ngắn rốt cuộc đều quy ra bao nhiêu mẩu.', related:['LLM','Prompt','Context window']},
  {name:'Context window', icon:'📏', cat:'AI', brief:'Lượng chữ tối đa AI nhìn được trong một lượt.', plain:'Context window là giới hạn số token model xem được cùng lúc, tính cả câu bạn hỏi lẫn phần nó trả lời.', analogy:'Như mặt bàn có hạn: bày thêm giấy tờ mới thì phải đẩy bớt tờ cũ ra, thứ rơi khỏi bàn coi như không còn thấy nữa.', related:['Token','Prompt','LLM']},
  {name:'Hallucination', icon:'🌫️', cat:'AI', brief:'AI nói sai nhưng nghe rất thuyết phục.', plain:'Hallucination là khi model tạo ra thông tin không có thật, như tên sách, số liệu hay trích dẫn, mà vẫn trình bày chắc nịch.', analogy:'Như người kể chuyện quá tự tin: chỗ nào quên thì bịa cho liền mạch, nghe trôi chảy nên người nghe khó nhận ra.', related:['LLM','RAG','Prompt']},
  {name:'Fine-tuning', icon:'🎚️', cat:'AI', brief:'Dạy thêm cho model có sẵn để hợp việc của bạn.', plain:'Fine-tuning là huấn luyện tiếp một model đã có trên dữ liệu riêng, để nó quen giọng văn hoặc nghiệp vụ cụ thể.', analogy:'Như tuyển người đã biết nghề rồi đào tạo thêm quy trình nội bộ, thay vì dạy lại từ con số không.', related:['Training','Model','Dataset']},
  {name:'RAG', icon:'📎', cat:'AI', brief:'Cho AI tra tài liệu trước khi trả lời.', plain:'RAG ghép model với một kho tài liệu: khi có câu hỏi, hệ thống tìm đoạn liên quan rồi đưa kèm vào prompt để câu trả lời có căn cứ.', analogy:'Như thi được mở tài liệu: thay vì moi từ trí nhớ, thí sinh lật đúng trang rồi mới trả lời nên ít nói bừa.', related:['Embedding','Hallucination','LLM']},
  {name:'Embedding', icon:'📍', cat:'AI', brief:'Biến chữ nghĩa thành toạ độ để so độ giống nhau.', plain:'Embedding chuyển văn bản hoặc ảnh thành dãy số, sao cho những thứ có nghĩa gần nhau thì nằm gần nhau.', analogy:'Như xếp sách thư viện theo chủ đề: đứng ở kệ nấu ăn thì quanh đó toàn sách nấu ăn, khỏi cần đọc tên từng cuốn.', related:['RAG','Dataset','Model']},
  {name:'Inference', icon:'🎯', cat:'AI', brief:'Lúc model chạy thật để trả kết quả.', plain:'Inference là giai đoạn dùng model đã huấn luyện xong để xử lý dữ liệu mới, khác với training là giai đoạn còn đang học.', analogy:'Học xong thì đến lúc hành nghề: training là đi học, inference là ngồi tiếp khách và xử lý từng ca.', related:['Model','Training','GPU']},
  {name:'GPU', icon:'🎮', cat:'AI', brief:'Chip chuyên tính song song, xương sống của AI.', plain:'GPU xử lý cùng lúc rất nhiều phép tính nhỏ, nên hợp với việc huấn luyện và chạy các model lớn.', analogy:'CPU là một thợ giỏi làm tuần tự từng việc; GPU là cả trăm thợ phụ cùng làm một loại việc đơn giản, nên xong nhanh hơn hẳn.', related:['Training','Inference','Cloud']},
  {name:'Bias', icon:'⚖️', cat:'AI', brief:'Thiên lệch học từ dữ liệu, dẫn tới kết quả thiếu công bằng.', plain:'Bias xảy ra khi dữ liệu huấn luyện mang sẵn định kiến hoặc thiếu đại diện, khiến model đối xử lệch với một số nhóm.', analogy:'Tuyển người mà chỉ nhìn theo hồ sơ cũ của công ty thì sẽ lặp lại đúng thói quen tuyển ngày trước, kể cả những thói quen sai.', related:['Dataset','Training','AI']},
  {name:'Agent', icon:'🦾', cat:'AI', brief:'AI tự lên kế hoạch và dùng công cụ để làm xong việc.', plain:'Agent dùng model làm bộ não: tự chia nhỏ mục tiêu, gọi công cụ hoặc API, rồi tự kiểm tra kết quả qua nhiều bước.', analogy:'Khác với hỏi đáp một lượt, agent giống trợ lý được giao việc: tự tra cứu, tự liên hệ chỗ cần, xong xuôi mới báo lại.', related:['LLM','API','Prompt']},
  {name:'Computer Vision', icon:'👁️', cat:'AI', brief:'Dạy máy nhìn và hiểu hình ảnh.', plain:'Computer Vision giúp máy nhận ra vật thể, khuôn mặt, chữ viết hay chuyển động trong ảnh và video.', analogy:'Như dạy người mới phân biệt biển báo giao thông: nhìn đủ nhiều rồi thì liếc qua là biết ngay biển nào.', related:['Deep Learning','Neural Network','Dataset']},
  {name:'NLP', icon:'🗣️', cat:'AI', brief:'Cho máy xử lý được tiếng người.', plain:'NLP là lĩnh vực giúp máy đọc hiểu, phân tích và tạo ra ngôn ngữ tự nhiên: dịch, tóm tắt, phân loại cảm xúc.', analogy:'Như phiên dịch viên đứng giữa người và máy, chuyển câu chữ lộn xộn đời thường thành thứ máy xử lý được.', related:['LLM','AI','Machine Learning']},
  {name:'Chatbot', icon:'💭', cat:'AI', brief:'Chương trình trò chuyện bằng ngôn ngữ tự nhiên.', plain:'Chatbot nhận câu hỏi bằng lời thường rồi trả lời lại; loại hiện đại dựa trên LLM nên bám ngữ cảnh tốt hơn kịch bản cứng ngày trước.', analogy:'Đời đầu giống tổng đài bấm phím theo menu có sẵn; đời nay giống nói chuyện với nhân viên hiểu được cả câu hỏi lòng vòng.', related:['LLM','Prompt','AI']},
  {name:'Overfitting', icon:'🎓', cat:'AI', brief:'Học thuộc lòng dữ liệu cũ, gặp cái mới là hỏng.', plain:'Overfitting là khi model khớp quá sát dữ liệu huấn luyện, thuộc cả phần nhiễu, nên làm rất tốt trên đề cũ mà kém hẳn với dữ liệu thật.', analogy:'Học tủ đúng đề năm ngoái: kiểm tra lại đề đó thì điểm cao, đổi đề một chút là trượt.', related:['Training','Dataset','Model']}
];

export const ALIASES = {
  'API':'giao dien lap trinh ket noi ung dung', 'Database':'co so du lieu du lieu', 'Server':'may chu',
  'Frontend':'giao dien phia nguoi dung', 'Backend':'phia may chu xu ly he thong', 'Cloud':'dien toan dam may',
  'Cache':'bo nho dem luu tam', 'Git':'quan ly phien ban ma nguon', 'Deploy':'trien khai phat hanh',
  'Bug':'loi phan mem', 'Debug':'sua loi tim loi', 'UI/UX':'thiet ke giao dien trai nghiem nguoi dung',
  'AI':'tri tue nhan tao', 'Machine Learning':'may hoc hoc may ml', 'Deep Learning':'hoc sau mang sau dl',
  'Neural Network':'mang no ron than kinh nhan tao', 'Model':'mo hinh', 'Training':'huan luyen dao tao',
  'Dataset':'tap du lieu bo du lieu', 'LLM':'mo hinh ngon ngu lon', 'Prompt':'cau lenh loi nhac yeu cau',
  'Token':'don vi chu mau chu', 'Context window':'cua so ngu canh gioi han ngu canh',
  'Hallucination':'ao giac bia dat noi sai', 'Fine-tuning':'tinh chinh huan luyen them',
  'RAG':'truy xuat tang cuong tra tai lieu', 'Embedding':'vector nhung bieu dien so',
  'Inference':'suy luan chay model du doan', 'GPU':'card do hoa chip xu ly do hoa',
  'Bias':'thien lech dinh kien', 'Agent':'tac tu tro ly tu dong',
  'Computer Vision':'thi giac may tinh nhan dien anh', 'NLP':'xu ly ngon ngu tu nhien',
  'Chatbot':'tro ly ao bot chat', 'Overfitting':'hoc tu qua khop'
};
